name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
      APPLE_DEVELOPER_TOKEN: ${{secrets.APPLE_DEVELOPER_TOKEN}}
      SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Say Hello Mona it's Monday"
        run: echo "$First_Name."
        env:
          First_Name: Wtf Mona
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Flake8
      run: |
        flake8 .
    - name: Run Tests
      run: |
        python manage.py test
